# This is a basic workflow to help you get started with Actions

name: CI Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup node.JS
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
      
      # Install dependencies
      - name: Run npm install
        run: npm install
    
  deploy:
    needs: build
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.f44ed4a3-1e41-4ded-9772-25e720a0b265}}
          heroku_app_name: "binar-team-one-backend"
          heroku_email: "teambinar@gmail.com"
